- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    grafana_login: admin
    grafana_password: admin
    grafana_url: http://127.0.0.1:3000/api/annotations
  tasks:

    - name: Create a global annotation without time information (login/passwd)
      grafana_annotations:
        url: "{{ grafana_url }}"
        url_username: "{{ grafana_login }}"
        url_password: "{{ grafana_password }}"
        text: "This is an annotation with automatic time value"
      register: anno
      tags:
        - base

    - name: Create a global annotation without time information (token)
      grafana_annotations:
        url: "{{ grafana_url }}"
        token: "{{ lookup('env','GRAFANA_API_TOKEN') }}"
        text: "This is an annotation with automatic time value"
      register: anno
      tags:
        - token

    - debug:
        var: anno
      tags:
        - token

    - set_fact:
        curdate: "{{ '%s' | strftime() | int}}"
      tags:
        - base
    
    - name: Create a global annotation with time annotation
      grafana_annotations:
        url: "{{ grafana_url }}"
        url_username: "{{ grafana_login }}"
        url_password: "{{ grafana_password }}"
        time: "{{ curdate }}"
        text: "This is an annotation explicitly set at {{ curdate }}"
        tags:
            - test-tag
      register: anno
      tags:
        - base

    - debug:
        var: anno
      tags:
        - base

    - name: test idempotence
      grafana_annotations:
        url: "{{ grafana_url }}"
        url_username: "{{ grafana_login }}"
        url_password: "{{ grafana_password }}"
        time: "{{ curdate }}"
        text: "This is an annotation explicitly set at {{ curdate }}"
        tags:
            - test-tag
      register: anno
      tags:
        - base

    - assert:
        that: not anno.changed
      tags:
        - base
